apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: external-secret
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  externalSecretSpec:
    refreshInterval: "30s"
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: postgres-keys
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: monospaced/database
  namespaceSelector:
    matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: In
      values:
      - monospaced
      - analytics