apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: external-secret
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-keys
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: monospaced/database