apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: postgres-keys
spec:
  externalSecretName: postgres-keys
  externalSecretSpec:
    refreshPolicy: Periodic
    refreshInterval: "30s"
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    target:
      name: postgres-keys
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: monospaced/database
  namespaceSelectors:
  - matchLabels:
      "kubernetes.io/metadata.name": "monospaced"
  - matchLabels:
      "kubernetes.io/metadata.name": "postgres"