apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: lens-secret
spec:
  externalSecretName: lens-secret
  refreshTime: "1m"
  namespaceSelectors:
  - matchLabels:
      "kubernetes.io/metadata.name": "lens-backend"
  - matchLabels:
      "kubernetes.io/metadata.name": "lens-frontend"
  - matchLabels:
      "kubernetes.io/metadata.name": "lens-consumer"
  externalSecretSpec:
    secretStoreRef:
      name: vault-backend
      kind: ClusterSecretStore
    refreshPolicy: Periodic
    refreshInterval: 1m
    target:
      name: lens-secret
      creationPolicy: Owner
    dataFrom:
    - extract:
        key: backend/lens