apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkerd-identity-issuer-secret
  namespace: linkerd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: linkerd-identity-issuer
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: linkerd/certificates
      property: issuer-ca
  - secretKey: tls.key
    remoteRef:
      key: linkerd/certificates
      property: issuer-key