kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: k8s-apps-project
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.27.0
      chart: istiod
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
