kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: linkerd-crds
  namespace: argocd
  annotations:
    "argocd.argoproj.io/sync-wave": "0"
spec:
  project: k8s-apps-project
  sources:
  - repoURL: https://helm.linkerd.io/edge
    chart: linkerd-crds
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: linkerd
    directory:
      include: trust-anchor-configmap.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true