apiVersion: apps/v1
kind: Deployment
metadata:
  name: monospaced-backend
  namespace: monospaced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monospaced-backend
  template:
    metadata:
      labels:
        app: monospaced-backend
    spec:
      nodeSelector:
        nodeRole: worker
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - monospaced-backend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: monospaced-backend
          image: ghcr.io/rohitpotato/monospaced-stack/backend:main-d368594
          imagePullPolicy: Always
          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=256"
          envFrom:
            - configMapRef:
                name: monospaced-backend-config
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "300m"
