apiVersion: v1
kind: Service
metadata:
  name: monospaced-backend
  namespace: monospaced
spec:
  selector:
    app: monospaced-backend
  ports:
    - name: http
      port: 5001
      targetPort: 5001
  type: ClusterIP