apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: k8s-apps-project
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.17.0
    helm:
      valueFiles:
      - $values/observability/promtail/values.yaml
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    ref: values
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true