loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  schema_config:
    configs:
      from: 2024-04-01
      object_store: filesystem
      store: boltdb-shipper
      schema: v13
      index:
        prefix: index_
        period: 24h
  limits_config:
    retention_period: 168h
  persistence:
    enabled: true
    size: 10Gi
  nodeSelector:
    nodeRole: worker
singleBinary:
  replicas: 1