apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agent-read-only
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-apps-project
  source:
    repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: rbac/agent-read-only
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
