apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: k8s-apps-project
  sources:
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: eso
    directory:
      include: cluster-secret-store.yaml
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: eso-secrets
    directory:
      include: db-keys.yaml
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: eso-secrets
    directory:
      include: linkerd-keys.yaml
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: eso-secrets
    directory:
      include: redis-keys.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true