apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: k8s-apps-project
  sources:
  - repoURL: https://github.com/argoproj/argo-helm.git
    targetRevision: main
    path: charts/argo-rollouts
    helm:
      valueFiles:
      - $values/argo-rollouts/values.yaml
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: argo-rollouts
    directory:
      include: rbac.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
