apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monospaced-backend
  namespace: argocd
spec:
  project: k8s-apps-project
  source:
    repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: HEAD
    path: backend/production/monospaced-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: monospaced
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true