apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monospaced-frontend
  namespace: argocd
  labels:
    name: monospaced-frontend
spec:
  project: k8s-apps-project
  source:
    repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: HEAD
    path: frontend/production/monospaced-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: monospaced
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true