apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: k8s-apps-project
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.28.1
      chart: vault
      helm:
        valueFiles:
          - $values/vault/values.yaml
    - repoURL: https://github.com/rohitpotato/k8s-apps.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
