apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lens-consumer
  namespace: backend
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: lens-consumer
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
