apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-apps-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/rohitpotato/k8s-apps.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'      # All API groups
      kind: '*'       # All kinds
