apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-apps-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/rohitpotato/k8s-apps.git
    - https://helm.releases.hashicorp.com
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: monospaced
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'      # All API groups
      kind: '*'       # All kinds
