apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: k8s-apps-project
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/rohitpotato/k8s-apps.git
    - https://helm.releases.hashicorp.com
    - https://prometheus-community.github.io/helm-charts
    - https://charts.external-secrets.io
    - https://grafana.github.io/helm-charts
    - https://linkerd.github.io/helm-charts/
  destinations:
    - namespace: monospaced
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: postgres
      server: https://kubernetes.default.svc
    - namespace: analytics
      server: https://kubernetes.default.svc
    - namespace: linkerd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'      # All API groups
      kind: '*'       # All kinds
