apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: argocd
  name: argocd-cm
data:
  exec.enabled: "true"