apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: k8s-apps-project
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 75.6.1
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/observability/values.yaml
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true