# Deployment type: Use 'deployment' for single pod (fine for single-node); change to 'daemonset' for multi-node to bind on all nodes
type: DaemonSet

# Enable host network to bind directly to host ports 80/443
hostNetwork: true

# Service config: ClusterIP since we're using hostNetwork (no LB or NodePort needed)
service:
  type: ClusterIP
  ports:
    # Limit to only HTTP/HTTPS to avoid conflicts; defaults include more (e.g., status-port 15021)
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

# Pod-level security context
securityContext:
  # Run as non-root user (default 1337)
  runAsUser: 1337
  runAsGroup: 1337
  fsGroup: 1337

# Container-level security context with capabilities
containerSecurityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false

# Optional: If multi-node, add nodeSelector or affinity as needed
# affinity: {}  # Customize if pinning to specific nodes