# Istio Gateway configuration for bare metal K3s
# Uses host ports 80 and 443 for HTTP/HTTPS traffic

# Deployment type: Use 'daemonset' for multi-node to bind on all nodes
type: DaemonSet

# Enable host network to bind directly to host ports 80/443
hostNetwork: true

# Service config: ClusterIP since we're using hostNetwork (no LB or NodePort needed)
service:
  type: ClusterIP
  ports:
    # Limit to only HTTP/HTTPS to avoid conflicts
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

# Security context for low-port binding
securityContext:
  capabilities:
    add:
      - NET_BIND_SERVICE
  runAsUser: 1337
  runAsGroup: 1337
  fsGroup: 1337

# Resource limits for bare metal
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 2000m
    memory: 1024Mi

# Optional: If multi-node, add nodeSelector or affinity as needed
# affinity: {}  # Customize if pinning to specific nodes