apiVersion: apps/v1
kind: Deployment
metadata:
  name: unami-analytics
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unami-analytics
  template:
    metadata:
      labels:
        app: unami-analytics
    spec:
      containers:
      - name: unami-analytics
        image: docker.umami.is/umami-software/umami:postgresql-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres-keys
                key: POSTGRES_URL