apiVersion: apps/v1
kind: Deployment
metadata:
  name: unami-analytics
  namespace: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unami-analytics
  template:
    metadata:
      labels:
        app: unami-analytics
    spec:
      containers:
      - name: unami-analytics
        image: docker.umami.is/umami-software/umami:postgresql-latest
        ports:
        - containerPort: 3000
          name: unami
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-keys
              key: POSTGRES_URL
        - name: DATABASE_TYPE
          value: postgresql
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"
