apiVersion: v1
kind: Service
metadata:
  name: unami-analytics
  namespace: analytics
spec:
  selector:
    app: unami-analytics
  ports:
  - protocol: TCP
    port: 3000
    targetPort: unami
  type: ClusterIP