apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd  # or whatever namespace ArgoCD is in
spec:
  project: k8s-apps-project

  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.28.1
      helm:
        valueFiles:
          - $values/vault/values.yaml
    - repoURL: https://github.com/rohitpotato/k8s-apps.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: vault

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

  ignoreDifferences:
  - group: "*"
    kind: "*"
    jsonPointers:
    - /metadata/annotations/helm.sh~1hook
    - /metadata/annotations/helm.sh~1hook-delete-policy
    - /metadata/annotations/helm.sh~1hook-succeeded
    - /metadata/annotations/helm.sh~1hook-weight
