server:
  ha:
    enabled: true
    raft:
      enabled: true

  volumes:
    - name: vault-tls
      secret:
        secretName: vault-tls

  volumeMounts:
    - name: vault-tls
      mountPath: /vault/userconfig/vault-tls
      readOnly: true

ui:
  enabled: true

injector:
  enabled: true
