server:
  ha:
    enabled: true
    replicas: 2
    raft:
      enabled: true
      # Add snapshot configuration for backup
      setCredentials: true
      snapshot:
        enabled: true
        interval: "1h"
        retain: 24  # Keep 24 snapshots
  standalone:
    enabled: false
    config: |
      ui = true
      
      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }
      
      storage "raft" {
        path = "/vault/data"
        retry_join {
          leader_api_addr = "http://vault-0.vault-internal:8200"
        }
        retry_join {
          leader_api_addr = "http://vault-1.vault-internal:8200"
        }
      }

ui:
  enabled: true

injector:
  enabled: true

dataStorage:
  enabled: true
  size: 5Gi
  storageClass: "local-path"  # Update this based on your actual storage class
  accessModes:
    - ReadWriteOnce
  finalizers:
    - kubernetes.io/pvc-protection

# Add pod disruption budget for HA
pdb:
  enabled: true
  maxUnavailable: 1
