server:
  ha:
    enabled: false
  standalone:
    enabled: true
    config: |
      ui = true
      
      listener "tcp" {
        address     = "0.0.0.0:8200"
        tls_disable = 1
      }
      storage "file" {
        path = "/vault/data"
      }

ui:
  enabled: true

injector:
  enabled: true

# Use ReadWriteOnce storage for single node
dataStorage:
  enabled: true
  size: 5Gi
  storageClass: "local-path"
  accessModes:
    - ReadWriteOnce
  finalizers:
    - kubernetes.io/pvc-protection

# Remove PDB for single node
pdb:
  enabled: false

# Resource limits for Vault pod
server:
  resources:
    requests:
      memory: "256Mi"
      cpu: "200m"
    limits:
      memory: "512Mi"
      cpu: "400m"
