apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-tls
  namespace: vault
spec:
  secretName: vault-tls
  duration: 2160h  # 90d
  renewBefore: 360h  # 15d
  subject:
    organizations:
    - monospaced
  commonName: vault.rohitpotato.xyz
  dnsNames:
  - vault.rohitpotato.xyz
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
