apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: k8s-apps-project
  source:
    repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: vault
    kustomize:
      buildOptions: "--enable-helm"
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
