apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: k8s-apps-project
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 22.0.7
    helm:
      valueFiles:
      - $values/redis/values.yaml
  - repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true