apiVersion: v1
kind: Service
metadata:
  name: lens-backend
  namespace: backend
spec:
  selector:
    app: lens-backend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
  type: ClusterIP