apiVersion: v1
kind: Service
metadata:
  name: lens
  namespace: frontend
  labels:
    app: lens
    stack: lens
spec:
  selector:
    app: lens
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: metrics
      port: 4040
      targetPort: 4040
  type: ClusterIP
