apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monospaced-frontend-ingress
  namespace: monospaced
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: rohitpotato.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monospaced-frontend
                port:
                  number: 3000
  tls:
    - hosts:
        - rohitpotato.xyz
      secretName: rohitpotato-xyz-tls