apiVersion: v1
kind: Service
metadata:
  name: monospaced-frontend-stable
  namespace: monospaced
  labels:
    app: monospaced-frontend
spec:
  selector:
    app: monospaced-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: metrics
      port: 4040
      targetPort: 4040
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: monospaced-frontend-canary
  namespace: monospaced
spec:
  selector:
    app: monospaced-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: metrics
      port: 4040
      targetPort: 4040
  type: ClusterIP