apiVersion: v1
kind: Service
metadata:
  name: monospaced-frontend
  namespace: monospaced
spec:
  selector:
    app: monospaced-frontend  
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP