apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monospaced-frontend
  namespace: monospaced
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: monospaced-frontend
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http