apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend 
spec:
  provider:
    vault: 
      server: "https://vault-active.vault-internal:8200"
      path: "kv" 
      version: "v2" 
      auth:
        tokenSecretRef: 
          name: "vault-token"
          key: "vault-token" 