# k8s-apps/scan-apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scan-apps
  namespace: argocd
spec:
  project: k8s-apps-project
  source:
    repoURL: https://github.com/rohitpotato/k8s-apps.git
    targetRevision: main
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true