kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-exporter-config
  namespace: monospaced
data:
  config.hcl: |
    listen {
      port = 4040
      address = "0.0.0.0"
    }

    namespace "nginx" {
      source = {
        files = ["/var/log/nginx/exporter-access.log"]
      }

      format = "json"
    }