# Configure external Prometheus
prometheus:
  enabled: false

# Node selector for worker nodes
nodeSelector:
  nodeRole: worker

# Pod anti-affinity for better distribution
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - linkerd-viz
        topologyKey: kubernetes.io/hostname

# Configure external Grafana
grafana:
  enabled: false

# External Prometheus URL (required when prometheus.enabled=false)
prometheusUrl: http://prometheus-operated.monitoring.svc.cluster.local:9090

# External Grafana URL
grafanaUrl: http://grafana.monitoring.svc.cluster.local:80

# Resource limits for Linkerd Viz components
web:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Tap component resource limits
tap:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Tap Injector component resource limits
tapInjector:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Dashboard component resource limits
dashboard:
  enforcedHostRegexp: ".*"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

# Metrics API component resource limits
metricsAPI:
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
